# Generated by Django 4.1.4 on 2022-12-18 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0002_post_last_updated_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='mitigation_progress',
            field=models.TextField(null=True),
        ),
    ]
